services:
  popcorn-palace:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/popcorn-palace
      SPRING_DATASOURCE_USERNAME: popcorn-palace
      SPRING_DATASOURCE_PASSWORD: popcorn-palace
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: popcorn-palace
      POSTGRES_PASSWORD: popcorn-palace
      POSTGRES_DB: popcorn-palace
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
